#!/bin/sh
# NIL-667: proves what nginx actually SENDS on the built frontend image, not
# what frontend/nginx.conf.template merely says. nginx only inherits a parent
# block's `add_header` directives when the current `location` sets none of
# its own -- a location that adds even one silently drops every inherited
# header. Reading the config file cannot catch that; only asking the running
# server can. See the CI job "Nginx Security Headers (NIL-667)" in
# .github/workflows/test.yml for how this gets a built image to point at.
#
# Usage: check-nginx-security-headers.sh <base-url>
# Exits non-zero and prints exactly which header(s) were missing where.
set -eu

BASE_URL="${1:?usage: check-nginx-security-headers.sh <base-url>}"
FAILED=0

# check_headers <label> <path> <expected-status>
check_headers() {
  label="$1"
  path="$2"
  expected_status="$3"
  headers=$(curl -s -D - -o /dev/null "${BASE_URL}${path}")
  status=$(printf '%s\n' "$headers" | head -1 | tr -d '\r' | awk '{print $2}')

  if [ "$status" != "$expected_status" ]; then
    echo "FAIL [$label] $path: expected HTTP $expected_status, got $status"
    FAILED=1
  fi

  # header_name:header_value_substring pairs, one per required header
  for pair in \
    "x-frame-options:DENY" \
    "x-content-type-options:nosniff" \
    "referrer-policy:no-referrer" \
    "permissions-policy:camera=()" \
    "content-security-policy:frame-ancestors 'none'"; do
    name="${pair%%:*}"
    expected_substring="${pair#*:}"
    value=$(printf '%s\n' "$headers" | tr -d '\r' | grep -i "^${name}:" | head -1 || true)
    case "$value" in
      *"$expected_substring"*) ;;
      *)
        echo "FAIL [$label] $path: missing or wrong '$name' header (got: '${value:-<absent>}')"
        FAILED=1
        ;;
    esac
  done

  if [ "$FAILED" -eq 0 ] || [ "${QUIET:-}" != "1" ]; then
    echo "checked [$label] $path (HTTP $status)"
  fi
}

# All three location blocks in frontend/nginx.conf.template that set their
# own add_header and used to lose the server-level security headers as a
# result (NIL-667) -- checked here so a guard exists for every one of them,
# not just some: `= /index.html`, `= /runtime-config.js`, and the cached
# static asset regex, plus an error response from the last one to prove
# `always` is doing its job.
check_headers "index.html" "/index.html" 200

# Generated by docker-entrypoint.sh on every container start and loaded by a
# <script> tag on every page load (index.html), same criticality as
# index.html itself -- caught missing from this check by Hans-Friedrich's
# review of PR #231.
check_headers "runtime-config.js" "/runtime-config.js" 200

ASSET_PATH=$(curl -s "${BASE_URL}/" | grep -o '/assets/[^"]*\.js' | head -1)
if [ -z "$ASSET_PATH" ]; then
  echo "FAIL: could not find a built JS asset reference in / to check"
  FAILED=1
else
  check_headers "cached asset (200)" "$ASSET_PATH" 200
fi
check_headers "cached asset (404)" "/assets/does-not-exist-nil667.js" 404

if [ "$FAILED" -ne 0 ]; then
  echo ""
  echo "One or more security headers are missing from what nginx actually sent."
  exit 1
fi

echo ""
echo "All required security headers present on every checked location and status."
