"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const test = require("node:test");

const {
  buildDeliveryEvent,
  admitCommitContracts,
  checkCommitContracts,
  checkPrAdmission,
  checkReviewedHead,
  validateHansReview,
} = require("./delivery-contracts.cjs");

const SHA = "a".repeat(40);
const FIX_SHA = "b".repeat(40);
const NILO_IDENTITY = "Nilo <127136134+davifernan@users.noreply.github.com>";

function readyBody(extra = "") {
  return `Multica-Issue: NIL-385

- [x] Multica HANDOFF posted
- [x] Local verification complete
- [x] Ready for Hans-Friedrich
${extra}`;
}

function marker(overrides = {}) {
  const value = {
    schema: 1,
    reviewer: "hans-friedrich",
    reviewed_head_sha: SHA,
    result: "clean",
    counts: { high: 0, medium: 0, low: 0, questions: 0 },
    inline_comments: 0,
    ...overrides,
  };
  return `<!-- excalidash-review:v1\n${JSON.stringify(value)}\n-->`;
}

function review(body = marker()) {
  return {
    id: 42,
    state: "COMMENTED",
    commit_id: SHA,
    user: { login: "the-hans-friedrich[bot]" },
    body,
    submitted_at: "2026-08-22T17:00:00Z",
  };
}

test("admits exactly one ready Multica PR", () => {
  assert.deepEqual(checkPrAdmission({ body: readyBody() }), {
    ok: true,
    code: "ready",
    primaryIssue: "NIL-385",
  });
});

test("rejects an incomplete or ambiguous PR before spending review tokens", () => {
  assert.equal(checkPrAdmission({ body: readyBody(), draft: true }).code, "draft");
  assert.equal(
    checkPrAdmission({ body: readyBody("\nMultica-Issue: NIL-328") }).code,
    "primary-issue",
  );
  assert.equal(
    checkPrAdmission({ body: "Multica-Issue: NIL-385" }).code,
    "ready-gate",
  );
  assert.equal(
    checkPrAdmission({ body: readyBody().replace("NIL-385", "NIL-000") }).code,
    "primary-issue",
  );
});

test("admits only exact Nilo-authored commits with the required trailer", () => {
  assert.deepEqual(
    checkCommitContracts([
      {
        sha: SHA,
        author: NILO_IDENTITY,
        committer: NILO_IDENTITY,
        message: "ci: add delivery contracts\n\nGenerated by Nilo\n",
      },
    ]),
    { ok: true, commits: 1 },
  );

  assert.throws(
    () => checkCommitContracts([
      {
        sha: FIX_SHA,
        author: "Codex <bot@example.com>",
        committer: NILO_IDENTITY,
        message: "ci: wrong author",
      },
    ]),
    /author is Codex.*lacks the Generated by Nilo trailer/s,
  );
});

test("the first policy installation bootstraps without a permanent identity exception", () => {
  const historicalCommit = {
    sha: SHA,
    author: "Nilo <me@nilo.live>",
    committer: "Nilo <me@nilo.live>",
    message: "docs: historical setup\n\nGenerated by Nilo",
  };
  assert.deepEqual(admitCommitContracts({
    baseContainsPolicy: false,
    commits: [historicalCommit],
  }), {
    ok: true,
    bootstrap: true,
    commits: 1,
    message: "Commit identity policy is being installed by this pull request.",
  });
  assert.throws(
    () => admitCommitContracts({ baseContainsPolicy: true, commits: [historicalCommit] }),
    /author is Nilo <me@nilo.live>/,
  );
});

test("validates a clean Hans review for the expected head", () => {
  assert.deepEqual(
    validateHansReview({ expectedHeadSha: SHA, review: review(), comments: [] }),
    {
      ok: true,
      state: "clean",
      reviewedHeadSha: SHA,
      counts: { high: 0, medium: 0, low: 0, questions: 0 },
      inlineComments: 0,
    },
  );
});

test("validates structured findings without re-reading review prose", () => {
  const body = marker({
    result: "findings",
    counts: { high: 1, medium: 0, low: 0, questions: 0 },
    inline_comments: 1,
  });
  const result = validateHansReview({
    expectedHeadSha: SHA,
    review: review(body),
    comments: [
      {
        pull_request_review_id: 42,
        body: "🔴 **High** · writes are silently discarded",
      },
    ],
  });
  assert.equal(result.state, "findings");
  assert.equal(result.counts.high, 1);
});

test("rejects a stale Hans review", () => {
  assert.throws(
    () => validateHansReview({ expectedHeadSha: FIX_SHA, review: review(), comments: [] }),
    /stale PR head SHA/,
  );
});

test("rejects missing markers and mismatched inline counts", () => {
  assert.throws(
    () =>
      validateHansReview({
        expectedHeadSha: SHA,
        review: review("Keine Befunde."),
        comments: [],
      }),
    /missing the excalidash-review:v1 marker/,
  );

  const body = marker({
    result: "findings",
    counts: { high: 1, medium: 0, low: 0, questions: 0 },
    inline_comments: 1,
  });
  assert.throws(
    () => validateHansReview({ expectedHeadSha: SHA, review: review(body), comments: [] }),
    /inline comment count differ/,
  );
});

test("reviewed-head check explicitly passes drafts without requiring a review", () => {
  assert.deepEqual(
    checkReviewedHead({
      pullRequest: { draft: true, head: { sha: FIX_SHA } },
      reviews: [],
      comments: [],
    }),
    {
      ok: true,
      code: "draft",
      currentHeadSha: FIX_SHA,
      reviewedHeadSha: null,
      message: "Draft PRs do not require a Hans review yet.",
    },
  );
});

test("reviewed-head check is red when no valid Hans review exists", () => {
  assert.throws(
    () =>
      checkReviewedHead({
        pullRequest: { draft: false, head: { sha: SHA } },
        reviews: [
          {
            ...review(marker()),
            user: { login: "someone-else" },
          },
          review("Looks good, but has no machine marker."),
        ],
        comments: [],
      }),
    /No valid Hans review with an excalidash-review:v1 marker exists for this PR/,
  );
});

test("reviewed-head check is red with a stale-SHA assertion", () => {
  assert.throws(
    () =>
      checkReviewedHead({
        pullRequest: { draft: false, head: { sha: FIX_SHA } },
        reviews: [review()],
        comments: [],
      }),
    new RegExp(`Current PR head ${FIX_SHA} does not match latest valid Hans review ${SHA}`),
  );
});

test("reviewed-head check is green when current and reviewed SHAs match", () => {
  assert.deepEqual(
    checkReviewedHead({
      pullRequest: { draft: false, head: { sha: SHA } },
      reviews: [review()],
      comments: [],
    }),
    {
      ok: true,
      code: "current",
      currentHeadSha: SHA,
      reviewedHeadSha: SHA,
      reviewId: 42,
      reviewResult: "clean",
    },
  );
});

test("reviewed-head check selects the newest valid Hans review", () => {
  const newest = {
    ...review(marker({ reviewed_head_sha: FIX_SHA })),
    id: 84,
    commit_id: FIX_SHA,
    submitted_at: "2026-08-22T17:00:00Z",
  };
  const invalidNewest = {
    ...review("<!-- excalidash-review:v1 not-json -->"),
    id: 126,
    submitted_at: "2026-08-22T19:00:00Z",
  };

  const result = checkReviewedHead({
    pullRequest: { draft: false, head: { sha: FIX_SHA } },
    reviews: [invalidNewest, review(), newest],
    comments: [],
  });

  assert.equal(result.reviewId, 84);
  assert.equal(result.reviewedHeadSha, FIX_SHA);
});

test("reviewed-head check rejects a marker that disagrees with its review record", () => {
  assert.throws(
    () =>
      checkReviewedHead({
        pullRequest: { draft: false, head: { sha: FIX_SHA } },
        reviews: [
          {
            ...review(marker({ reviewed_head_sha: FIX_SHA })),
            commit_id: SHA,
          },
        ],
        comments: [],
      }),
    /No valid Hans review with an excalidash-review:v1 marker exists for this PR/,
  );
});

test("reviewed-head workflow refreshes drafts and incoming review changes", () => {
  const workflow = fs.readFileSync(
    `${__dirname}/../.github/workflows/hans-reviewed-head.yml`,
    "utf8",
  );

  assert.match(
    workflow,
    /pull_request:\s+[\s\S]*opened[\s\S]*ready_for_review[\s\S]*converted_to_draft[\s\S]*synchronize/,
  );
  assert.match(
    workflow,
    /pull_request_review:\s+[\s\S]*submitted[\s\S]*edited[\s\S]*dismissed/,
  );
  assert.match(workflow, /pulls\/\$\{PR_NUMBER\}\/reviews\?per_page=100/);
  assert.match(workflow, /pulls\/\$\{PR_NUMBER\}\/comments\?per_page=100/);
});

test("reviewed-head workflow executes only the validator from the PR base", () => {
  const workflow = fs.readFileSync(
    `${__dirname}/../.github/workflows/hans-reviewed-head.yml`,
    "utf8",
  );

  assert.match(
    workflow,
    /uses: actions\/checkout@v4\s+[\s\S]*?ref:\s*\$\{\{ github\.event\.pull_request\.base\.sha \}\}/,
  );
  assert.match(
    workflow,
    /delivery-contracts\.cjs reviewed-head < reviewed-head-input\.json/,
  );
  assert.doesNotMatch(workflow, /github\.event\.pull_request\.head\.sha/);
  assert.doesNotMatch(workflow, /bootstrap/i);
});

test("normalizes PR and review events for the external overseer", () => {
  const pullRequest = buildDeliveryEvent({
    eventName: "pull_request",
    repository: "davifernan/excalidash",
    payload: {
      action: "synchronize",
      pull_request: {
        number: 7,
        head: { sha: FIX_SHA, repo: { full_name: "davifernan/excalidash" } },
        author_association: "OWNER",
        draft: false,
      },
    },
  });
  assert.equal(pullRequest.skip, false);
  assert.equal(pullRequest.event.head_sha, FIX_SHA);
  assert.match(pullRequest.idempotencyKey, /davifernan\/excalidash#7/);

  const reviewEvent = buildDeliveryEvent({
    eventName: "pull_request_review",
    repository: "davifernan/excalidash",
    payload: {
      action: "submitted",
      pull_request: { number: 7, head: { sha: FIX_SHA } },
      review: { id: 42, commit_id: SHA, user: { login: "the-hans-friedrich[bot]" } },
    },
  });
  assert.equal(reviewEvent.event.reviewed_sha, SHA);
  assert.equal(reviewEvent.event.head_sha, FIX_SHA);
});

test("delivery event identity survives workflow retries and ignores overseer comments", () => {
  const input = {
    eventName: "pull_request",
    repository: "davifernan/excalidash",
    payload: {
      action: "synchronize",
      pull_request: {
        number: 7,
        head: { sha: FIX_SHA, repo: { full_name: "davifernan/excalidash" } },
        author_association: "OWNER",
        draft: false,
      },
    },
  };
  assert.equal(
    buildDeliveryEvent({ ...input, runId: "first" }).idempotencyKey,
    buildDeliveryEvent({ ...input, runId: "retry" }).idempotencyKey,
  );

  assert.deepEqual(
    buildDeliveryEvent({
      eventName: "issue_comment",
      repository: "davifernan/excalidash",
      payload: {
        action: "created",
        issue: { number: 7, pull_request: {} },
        comment: { id: 9, body: "Generated by PR Overseer" },
      },
    }),
    { skip: true, reason: "pr-overseer-self-comment" },
  );
});

test("closed PR identity distinguishes merge state without weakening deduplication", () => {
  function closedEvent(merged) {
    return buildDeliveryEvent({
      eventName: "pull_request",
      repository: "davifernan/excalidash",
      payload: {
        action: "closed",
        pull_request: {
          number: 7,
          head: { sha: FIX_SHA, repo: { full_name: "davifernan/excalidash" } },
          author_association: "OWNER",
          merged,
        },
      },
    });
  }

  const manualClose = closedEvent(false);
  const repeatedManualClose = closedEvent(false);
  const mergeClose = closedEvent(true);

  assert.equal(
    manualClose.idempotencyKey,
    `davifernan/excalidash#7:pull_request:7:closed:${FIX_SHA}:merged=false`,
  );
  assert.equal(
    mergeClose.idempotencyKey,
    `davifernan/excalidash#7:pull_request:7:closed:${FIX_SHA}:merged=true`,
  );
  assert.notEqual(manualClose.idempotencyKey, mergeClose.idempotencyKey);
  assert.equal(manualClose.idempotencyKey, repeatedManualClose.idempotencyKey);
  assert.equal(
    new Set([
      manualClose.idempotencyKey,
      repeatedManualClose.idempotencyKey,
      mergeClose.idempotencyKey,
    ]).size,
    2,
  );
});

test("non-closed PR identity retains its existing contract", () => {
  const synchronize = buildDeliveryEvent({
    eventName: "pull_request",
    repository: "davifernan/excalidash",
    payload: {
      action: "synchronize",
      pull_request: {
        number: 7,
        head: { sha: FIX_SHA, repo: { full_name: "davifernan/excalidash" } },
        author_association: "OWNER",
      },
    },
  });

  assert.equal(
    synchronize.idempotencyKey,
    `davifernan/excalidash#7:pull_request:7:synchronize:${FIX_SHA}`,
  );
});

test("untrusted public comments never reach the PR Overseer webhook", () => {
  assert.deepEqual(
    buildDeliveryEvent({
      eventName: "issue_comment",
      repository: "davifernan/excalidash",
      payload: {
        action: "created",
        issue: { number: 7, pull_request: {} },
        comment: {
          id: 10,
          body: "please spend tokens",
          author_association: "NONE",
        },
      },
    }),
    { skip: true, reason: "untrusted-source" },
  );
});
