"use strict";

const assert = require("node:assert/strict");
const { spawnSync } = require("node:child_process");
const path = require("node:path");
const test = require("node:test");

const { buildDeliveryEvent } = require("./delivery-contracts.cjs");

const scriptPath = path.join(__dirname, "pr-overseer-event-log.cjs");

function runSkipLog(payload, extraEnv = {}) {
  return spawnSync(process.execPath, [scriptPath], {
    encoding: "utf8",
    env: {
      ...process.env,
      PAYLOAD: JSON.stringify(payload),
      ...extraEnv,
    },
  });
}

test("reports every normalized skip reason and preserves the non-PR explanation", () => {
  const repository = "davifernan/excalidash";
  const cases = [
    [
      buildDeliveryEvent({
        eventName: "issue_comment",
        repository,
        payload: {
          action: "created",
          issue: { number: 7, pull_request: {} },
          comment: { body: "Generated by PR Overseer" },
        },
      }),
      "Event skipped: pr-overseer-self-comment\n",
    ],
    [
      buildDeliveryEvent({
        eventName: "issue_comment",
        repository,
        payload: {
          action: "created",
          issue: { number: 7, pull_request: {} },
          comment: { author_association: "NONE" },
        },
      }),
      "Event skipped: untrusted-source\n",
    ],
    [
      buildDeliveryEvent({
        eventName: "pull_request",
        repository,
        payload: {
          action: "opened",
          pull_request: {
            head: { repo: { full_name: repository } },
            author_association: "OWNER",
          },
        },
      }),
      "Event skipped: event-without-pr\nEvent does not belong to a pull request.\n",
    ],
    [
      buildDeliveryEvent({
        eventName: "workflow_run",
        repository,
        payload: { workflow_run: { pull_requests: [] } },
      }),
      "Event skipped: workflow-run-without-pr\n",
    ],
    [
      buildDeliveryEvent({ eventName: "issue_comment", repository, payload: {} }),
      "Event skipped: unsupported-issue_comment\n",
    ],
  ];

  for (const [payload, expectedOutput] of cases) {
    const result = runSkipLog(payload);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(result.stdout, expectedOutput);
    assert.equal(result.stderr, "");
  }
});

test("logs only a safe reason, never other normalized payload fields", () => {
  const result = runSkipLog(
    {
      skip: true,
      reason: "untrusted-source",
      event: {
        token: "secret-token-must-not-appear",
        webhook: "https://wake.invalid/private-endpoint",
      },
    },
    {
      WEBHOOK: "https://wake.invalid/actual-secret-endpoint",
      WAKE_TOKEN: "secret-environment-token-must-not-appear",
    },
  );

  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stdout, "Event skipped: untrusted-source\n");
  assert.doesNotMatch(result.stdout, /secret|private-endpoint|webhook|wake\.invalid/);
  assert.equal(result.stderr, "");
});

test("rejects an unsafe reason without reflecting it into the log", () => {
  const result = runSkipLog({
    skip: true,
    reason: "untrusted-source\nsecret-token-must-not-appear",
  });

  assert.equal(result.status, 1);
  assert.equal(result.stdout, "");
  assert.equal(result.stderr, "Skip reason is missing or unsafe.\n");
  assert.doesNotMatch(result.stderr, /secret-token/);
});
